### PR TITLE
Implement GitLab merge requests

### PR DESCRIPTION
**Pull request by gl-njanz**
Implements a function to count open [Merge Requests](https://docs.gitlab.com/ee/user/project/merge_requests/) that are assigned to the Personal Access Tokens user.

(And by implemented, I mean heavily borrowed from `GitLabTodos` of course 🙈 )

Waiting for #65 to be merged so I can finish up the documentation.

### CODE REVIEW

**Comment by SantiMA10** [comment]
@gl-njanz previous PR merged! Feel free to finish the documentation!

Let me try to prepare a few different images for the MR count

**Comment by SantiMA10** [comment]
# haveMRsImage
haveMRsImage

# haveMRsImage@2x
haveMRsImage@2x

# noMRsImage
noMRsImage

# noMRsImage@2x
noMRsImage@2x

**Comment by gl-njanz** [comment]
Thank you for the images @SantiMA10 

GitLab has recently rebranded, here's the new logo: https://about.gitlab.com/press/press-kit/

**Comment by gl-njanz** [comment]
I drafted some icons. I dropped the "MR closed" badge from the `noMRsImage`.
The intention behind it was to simplify the iconography, while also increasing the visibility when something needs your attention. Hope that's OK

**Comment by SantiMA10** [comment]
@gl-njanz Thanks for the new feature, I will update the other GitLab images and then send the update to the elgato store! 🚀

**Comment by gl-njanz** [comment]
Apologies for the ping @SantiMA10, have you had time to push the update?

**Comment by SantiMA10** [comment]
Ups, I totally forget about it @gl-njanz 🤦 

Sorry for the delay, I will send it to elgato this week

**Pull request merged**
